### PR TITLE
link fix

### PR DESCRIPTION
**Pull request by mrbar42**
also clean up old .idea file

### CODE REVIEW

**Comment by shaharmor** [comment]
@mrbar42 remove the entire `.idea` directory from this repo and add it to `.gitignore` please

**Comment by mrbar42** [comment]
`.idea` already added to `.gitignore` long ago... this is some stale files that were commited before it was added

**Comment by shaharmor** [comment]
good, so lets remove them

**Comment by mrbar42** [comment]
I removed them on the initial commit, but WS distorted it somehow - now all removed

**Pull request merged**
