### PR TITLE
complete docs overhaul

### PR DESCRIPTION
**Pull request by shaharmor**
Fixes https://github.com/Peer5/peer5-api/issues/14
Related to https://github.com/Peer5/peer5-api/issues/19

PREVIEW: https://5a0325934c4b9346e6f94b41--speaker-sources-67842.netlify.com/

- add server API docs (Not hidden)
- change theme to https://github.com/squidfunk/mkdocs-material - what we had stopped working and is not maintained.
- add code highlighting to all code blocks (Including nginx!)

### CODE REVIEW

**Comment by benjamingr** [comment]
Looks nice, had a quick look - some feedback:

 - What about the other API endpoints?
 - Search + enter doesn't work which is a little frustrating.
 - Some code highlights are lacking space or line numbers, [example](https://5a0325934c4b9346e6f94b41--speaker-sources-67842.netlify.com/guides/production-ready-hls-vod/#multiple-renditions).
 - I think we need more margin from the bottom in guides and pages [example of page without enough margin imo](https://5a0325934c4b9346e6f94b41--speaker-sources-67842.netlify.com/platforms/web/). 
 - In the responsive version (shrinking it to tablet size) the logo in the left menu looks clamped.


Unrelated but fixing is nice:

 - I noticed that the capitalization is off on [Optimizing Stream for efficient P2P](https://docs.peer5.com/overview/#optimizing-stream-for-efficient-p2p).

**Comment by shaharmor** [comment]
> What about the other API endpoints?

I'll add them later

> Search + enter doesn't work which is a little frustrating.

It does work, but you have to use the arrow keys to select the article you want

> Some code highlights are lacking space or line numbers

Fixed that example, let me know if you find others

> I think we need more margin from the bottom in guides and pages

Increased

> In the responsive version (shrinking it to tablet size) the logo in the left menu looks clamped.

Fixed

> I noticed that the capitalization is off on Optimizing Stream for efficient P2P.

Fixed

**Comment by mrbar42** [comment]
looks great.

>Search + enter doesn't work which is a little frustrating.

i actual had a custom [js script](https://github.com/Peer5/peer5-docs/blob/overhaul/docs/js/extra.js#L10) that fixed different bug in the previous theme.
it should be updated to solve this bug

**Comment by shaharmor** [comment]
@mrbar42 it has already been removed.

**Comment by benjamingr** [comment]
@shaharmor @mrbar42 this change broke a bunch of URLs, can either of you add 301s from the server?

https://docs.peer5.com/client-api/configuring-peer5/ for example works, but Google indexed https://docs.peer5.com/apis/configuring-peer5/ returns 404.

**Comment by mrbar42** [comment]
@benjamingr the way to do that is to add a `_redirects` file in `docs/_redirects`
netlify accepts rules in a format described [here](https://www.netlify.com/docs/redirects/)
```
/apis/configuring-peer5         /client-api/configuring-peer5        301
```

Do you have a list of such pages?

**Comment by benjamingr** [comment]
@mrbar42 looking at the PR I can only name two and in both cases it's `apis` -> `client-apis`.

**Pull request merged**
