### PR TITLE
Update wowza recommendations

### LINKED ISSUE #94: Update wowza recommendations
cupertinoPlaylistChunkCount: 20
cupertinoChunkDurationTarget: 5000
cupertinoMaxChunkCount: 30

### PR DESCRIPTION
**Pull request by benjamingr**
Fixes #94

### CODE REVIEW

**Comment by shaharmor** [comment]
@benjamingr You're missing the `cupertinoMaxChunkCount` parameter as listed in the issue

**Comment by benjamingr** [comment]
@shaharmor I didn't find it anywhere so I didn't update it - would you like me to add it? 

```
<Property>
    <Name>cupertinoMaxChunkCount</Name>
    <Value>30</Value>
    <Type>Integer</Type>
</Property>
```

**Comment by shaharmor** [comment]
@benjamingr Yes please. You are correct, its not listed today and we want to add it. Make sure you add it in both locations where config is mentioned

**Comment by benjamingr** [comment]
@shaharmor PTAL

**Comment by benjamingr** [comment]
Both changes SGTM, applied

**Comment by shaharmor** [comment]
We need to update the image as well, or remove it

**Comment by benjamingr** [comment]
@shaharmor I saw the image is different (in their docs), we can steal the image from their docs but I didn't want to do it because copyright - since we have a wowza install - can you log in and do a snapshot (or show me how to) and I'll make a PR?

**Comment by shaharmor** [comment]
@benjamingr 

screen shot 2017-07-05 at 12 50 48

**Comment by benjamingr** [comment]
Thanks, while I do this I might want to fix the wowza CORS issue as well.

**Pull request merged**
